"""Add assigned_rm_id

Revision ID: af85d06112b7
Revises: fffa208f7a23
Create Date: 2026-08-21 02:09:06.882096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af85d06112b7'
down_revision: Union[str, None] = 'fffa208f7a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('golden_records', sa.Column('assigned_rm_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_golden_records_assigned_rm_id'), 'golden_records', ['assigned_rm_id'], unique=False)
    op.create_foreign_key(None, 'golden_records', 'users', ['assigned_rm_id'], ['id'])
    op.add_column('source_records', sa.Column('assigned_rm_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_source_records_assigned_rm_id'), 'source_records', ['assigned_rm_id'], unique=False)
    op.create_foreign_key(None, 'source_records', 'golden_records', ['golden_record_id'], ['id'])
    op.create_foreign_key(None, 'source_records', 'users', ['assigned_rm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_records', type_='foreignkey')
    op.drop_constraint(None, 'source_records', type_='foreignkey')
    op.drop_index(op.f('ix_source_records_assigned_rm_id'), table_name='source_records')
    op.drop_column('source_records', 'assigned_rm_id')
    op.drop_constraint(None, 'golden_records', type_='foreignkey')
    op.drop_index(op.f('ix_golden_records_assigned_rm_id'), table_name='golden_records')
    op.drop_column('golden_records', 'assigned_rm_id')
    # ### end Alembic commands ###
