"""Initial schema

Revision ID: fffa208f7a23
Revises: 
Create Date: 2026-08-20 16:22:21.421127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'fffa208f7a23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('config_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_rules_id'), 'config_rules', ['id'], unique=False)
    op.create_index(op.f('ix_config_rules_rule_type'), 'config_rules', ['rule_type'], unique=True)
    op.create_table('golden_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_relationship_value', sa.Float(), nullable=True),
    sa.Column('products_held', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_systems', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source_record_count', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_records_id'), 'golden_records', ['id'], unique=False)
    op.create_index(op.f('ix_golden_records_pan'), 'golden_records', ['pan'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=True),
    sa.Column('raw_pan', sa.String(length=20), nullable=True),
    sa.Column('raw_mobile', sa.String(length=20), nullable=True),
    sa.Column('raw_email', sa.String(length=255), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('account_value', sa.Float(), nullable=True),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vector_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('golden_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_email'), 'source_records', ['email'], unique=False)
    op.create_index(op.f('ix_source_records_golden_record_id'), 'source_records', ['golden_record_id'], unique=False)
    op.create_index(op.f('ix_source_records_id'), 'source_records', ['id'], unique=False)
    op.create_index(op.f('ix_source_records_mobile'), 'source_records', ['mobile'], unique=False)
    op.create_index(op.f('ix_source_records_pan'), 'source_records', ['pan'], unique=False)
    op.create_index(op.f('ix_source_records_source_system'), 'source_records', ['source_system'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('RM', 'MANAGER', 'ADMIN', 'CREDIT_APPROVER', name='userrole'), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('identity_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_a_id', sa.Integer(), nullable=False),
    sa.Column('source_record_b_id', sa.Integer(), nullable=False),
    sa.Column('golden_record_id', sa.Integer(), nullable=True),
    sa.Column('match_phase', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['golden_record_id'], ['golden_records.id'], ),
    sa.ForeignKeyConstraint(['source_record_a_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['source_record_b_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_edges_golden_record_id'), 'identity_edges', ['golden_record_id'], unique=False)
    op.create_index(op.f('ix_identity_edges_id'), 'identity_edges', ['id'], unique=False)
    op.create_index(op.f('ix_identity_edges_source_record_a_id'), 'identity_edges', ['source_record_a_id'], unique=False)
    op.create_index(op.f('ix_identity_edges_source_record_b_id'), 'identity_edges', ['source_record_b_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('golden_record_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'VIEWED', 'ASSIGNED', 'IN_PROGRESS', 'CONVERTED', 'DISMISSED', name='opportunitystatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['golden_record_id'], ['golden_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_golden_record_id'), 'opportunities', ['golden_record_id'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_a_id', sa.Integer(), nullable=False),
    sa.Column('source_record_b_id', sa.Integer(), nullable=False),
    sa.Column('match_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_record_a_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['source_record_b_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_id'), 'review_queue', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_golden_record_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_identity_edges_source_record_b_id'), table_name='identity_edges')
    op.drop_index(op.f('ix_identity_edges_source_record_a_id'), table_name='identity_edges')
    op.drop_index(op.f('ix_identity_edges_id'), table_name='identity_edges')
    op.drop_index(op.f('ix_identity_edges_golden_record_id'), table_name='identity_edges')
    op.drop_table('identity_edges')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_records_source_system'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_pan'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_mobile'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_golden_record_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_email'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_golden_records_pan'), table_name='golden_records')
    op.drop_index(op.f('ix_golden_records_id'), table_name='golden_records')
    op.drop_table('golden_records')
    op.drop_index(op.f('ix_config_rules_rule_type'), table_name='config_rules')
    op.drop_index(op.f('ix_config_rules_id'), table_name='config_rules')
    op.drop_table('config_rules')
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
