/**
 * Nexus360 — Realistic Corporate Mock Data
 * Used as fallback if backend is offline during frontend demonstrations.
 */

export const MOCK_DEMO_USERS = [
  {
    username: 'admin',
    email: 'admin@nexus360.com',
    password: 'adminpassword123',
    full_name: 'Anand Mahindra (VP Tech & Ops)',
    role: 'ADMIN',
    description: 'Full administrative access across all 5 financial lines',
  },
  {
    username: 'reviewer_sarah',
    email: 'reviewer@nexus360.com',
    password: 'reviewerpassword123',
    full_name: 'Sarah Chen (Lead KYC Officer)',
    role: 'REVIEWER',
    description: 'Human-in-the-Loop review queue, manual merge & customer 360',
  },
  {
    username: 'rm_rajesh',
    email: 'rm@nexus360.com',
    password: 'rmpassword123',
    full_name: 'Rajesh Sharma (Senior RM — Wealth)',
    role: 'RELATIONSHIP_MANAGER',
    description: 'Opportunities dashboard, portfolio insights & customer 360',
  },
  {
    username: 'analyst_priya',
    email: 'analyst@nexus360.com',
    password: 'analystpassword123',
    full_name: 'Priya Nair (Risk & Compliance Analyst)',
    role: 'ANALYST',
    description: 'Read-only analytics, what-if simulations with PII masked',
  },
];

export const MOCK_OVERVIEW_STATS = {
  total_source_records: 12450,
  total_golden_records: 4890,
  match_rate_pct: 60.7,
  total_pairs_evaluated: 18230,
  total_matches: 7560,
  total_reviews_pending: 18,
  total_non_matches: 10652,
  total_relationship_value: 1845000000, // ₹184.5 Cr
  by_source_system: {
    EQUITY: { total_records: 3120, pan_completeness_pct: 98.4, missing_pan_count: 50 },
    MUTUAL_FUND: { total_records: 3450, pan_completeness_pct: 96.1, missing_pan_count: 135 },
    INSURANCE: { total_records: 2180, pan_completeness_pct: 84.5, missing_pan_count: 338 },
    LOAN: { total_records: 1980, pan_completeness_pct: 99.2, missing_pan_count: 16 },
    WEALTH: { total_records: 1720, pan_completeness_pct: 99.8, missing_pan_count: 3 },
  },
};

export const MOCK_CUSTOMERS = [
  {
    id: 1,
    golden_customer_id: 'GOLD-000101',
    canonical_name: 'Rohit P. Raghavan',
    canonical_dob: '1988-06-12',
    canonical_mobile: '9920602745',
    canonical_email: 'rohitaraghavan10@gmail.com',
    canonical_pan: 'ABCDE1234F',
    canonical_city: 'Mumbai',
    canonical_segment: 'HNI',
    total_relationship_value: 12850000,
    products_held: ['EQUITY', 'MUTUAL_FUND', 'WEALTH', 'INSURANCE'],
    source_record_ids: [101, 204, 309, 412],
    match_confidence: 0.94,
    status: 'ACTIVE',
    assigned_rm_id: 'RM-MUM-04',
    created_at: '2026-08-15T10:30:00Z',
    updated_at: '2026-08-19T14:20:00Z',
    attribute_provenance: {
      canonical_name: { source: 'WEALTH', rule: 'SOURCE_PRECEDENCE' },
      canonical_pan: { source: 'EQUITY', rule: 'SOURCE_PRECEDENCE' },
      canonical_mobile: { source: 'BANKING', rule: 'RECENCY' },
      canonical_email: { source: 'MUTUAL_FUND', rule: 'RECENCY' },
      canonical_city: { source: 'WEALTH', rule: 'SOURCE_PRECEDENCE' },
    },
    linked_sources: [
      {
        id: 101,
        source_system: 'WEALTH',
        source_record_id: 'WLT-8849',
        original_name: 'Rohit P. Raghavan',
        balance_aum: 8500000,
        product_type: 'Portfolio Management Services (PMS)',
        match_confidence: 0.98,
        match_method: 'DETERMINISTIC',
      },
      {
        id: 204,
        source_system: 'EQUITY',
        source_record_id: 'EQ-49201',
        original_name: 'Rohit Raghavan',
        balance_aum: 3200000,
        product_type: 'Direct Equity Demat',
        match_confidence: 0.95,
        match_method: 'FUZZY',
      },
      {
        id: 309,
        source_system: 'MUTUAL_FUND',
        source_record_id: 'MF-77312',
        original_name: 'R. P. Raghavan',
        balance_aum: 950000,
        product_type: 'Systematic Investment Plan (SIP)',
        match_confidence: 0.89,
        match_method: 'SEMANTIC',
      },
      {
        id: 412,
        source_system: 'INSURANCE',
        source_record_id: 'INS-1094',
        original_name: 'Rohit Raghavan',
        balance_aum: 200000,
        product_type: 'Term Life Cover (₹2 Cr)',
        match_confidence: 0.94,
        match_method: 'DETERMINISTIC',
      },
    ],
  },
  {
    id: 2,
    golden_customer_id: 'GOLD-000102',
    canonical_name: 'Sunita Mehra',
    canonical_dob: '1975-11-24',
    canonical_mobile: '9920602745',
    canonical_email: 'sunita.mehra@corporate.in',
    canonical_pan: 'BKMPM4920K',
    canonical_city: 'Delhi',
    canonical_segment: 'Ultra HNI',
    total_relationship_value: 45000000,
    products_held: ['WEALTH', 'LOAN', 'MUTUAL_FUND'],
    source_record_ids: [105, 218],
    match_confidence: 0.98,
    status: 'ACTIVE',
    assigned_rm_id: 'RM-DEL-01',
    created_at: '2026-08-16T11:00:00Z',
    updated_at: '2026-08-18T16:45:00Z',
  },
  {
    id: 3,
    golden_customer_id: 'GOLD-000103',
    canonical_name: 'Vikram Aditya Singhania',
    canonical_dob: '1982-03-15',
    canonical_mobile: '9920602745',
    canonical_email: 'vikram.singhania@singhania.com',
    canonical_pan: 'AAACS1928L',
    canonical_city: 'Bengaluru',
    canonical_segment: 'Corporate Promoter',
    total_relationship_value: 89000000,
    products_held: ['EQUITY', 'LOAN', 'WEALTH'],
    source_record_ids: [110, 222, 333],
    match_confidence: 0.91,
    status: 'ACTIVE',
    assigned_rm_id: 'RM-BLR-02',
    created_at: '2026-08-17T09:15:00Z',
    updated_at: '2026-08-20T12:00:00Z',
  },
];

export const MOCK_REVIEW_CASES = [
  {
    id: 1,
    match_decision_id: 14,
    priority: 'HIGH',
    status: 'PENDING',
    review_type: 'LOW_CONFIDENCE_MATCH',
    reviewer: null,
    created_at: '2026-08-20T08:30:00Z',
    ai_suggestion: 'Review candidate pair: Name similarity (0.92) and Mobile match (1.0) are strong, but PAN differs in 1 character due to potential transcription typo.',
    source_record_ids: [101, 102],
    record_a: {
      id: 101,
      source_system: 'EQUITY',
      source_record_id: 'EQ-8819',
      original_name: 'Vikram Aditya Singhania',
      original_dob: '1982-03-15',
      original_mobile: '9811234567',
      original_email: 'vikram.singhania@singhania.com',
      original_pan: 'AAACS1928L',
      original_city: 'Bengaluru',
      segment: 'Corporate',
      balance_aum: 45000000,
    },
    record_b: {
      id: 102,
      source_system: 'MUTUAL_FUND',
      source_record_id: 'MF-4402',
      original_name: 'Vikram A. Singhania',
      original_dob: '1982-03-15',
      original_mobile: '9811234567',
      original_email: 'vikram.s@singhania.com',
      original_pan: 'AAACS1928K',
      original_city: 'Bangalore',
      segment: 'HNI',
      balance_aum: 18000000,
    },
    field_comparisons: [
      { field_name: 'PAN Number', value_a: 'AAACS1928L', value_b: 'AAACS1928K', status: 'DIFFERENT', weight: 0.35, score: 0.0 },
      { field_name: 'Mobile Number', value_a: '9811234567', value_b: '9811234567', status: 'MATCH', weight: 0.20, score: 1.0 },
      { field_name: 'Full Name', value_a: 'Vikram Aditya Singhania', value_b: 'Vikram A. Singhania', status: 'PARTIAL', weight: 0.12, score: 0.92 },
      { field_name: 'Semantic Match', value_a: 'Corporate Demat', value_b: 'HNI Portfolio', status: 'MATCH', weight: 0.08, score: 0.94 },
      { field_name: 'Email Address', value_a: 'vikram.singhania@singhania.com', value_b: 'vikram.s@singhania.com', status: 'PARTIAL', weight: 0.15, score: 0.85 },
      { field_name: 'Date of Birth', value_a: '1982-03-15', value_b: '1982-03-15', status: 'MATCH', weight: 0.05, score: 1.0 },
      { field_name: 'City / Region', value_a: 'Bengaluru', value_b: 'Bangalore (Alias match)', status: 'MATCH', weight: 0.03, score: 1.0 },
      { field_name: 'Customer Segment', value_a: 'Corporate', value_b: 'HNI', status: 'MATCH', weight: 0.02, score: 1.0 },
    ],
    final_score: 0.764,
  },
  {
    id: 2,
    match_decision_id: 15,
    priority: 'MEDIUM',
    status: 'PENDING',
    review_type: 'ATTRIBUTE_CONFLICT',
    ai_suggestion: 'High confidence match on PAN (ABCDE1234F) and Name (0.95), but different mobile numbers recorded in Wealth vs Insurance system.',
    created_at: '2026-08-20T09:15:00Z',
    record_a: {
      id: 201,
      source_system: 'WEALTH',
      original_name: 'Rohit P. Raghavan',
      original_pan: 'ABCDE1234F',
      original_mobile: '9876543210',
      original_city: 'Mumbai',
    },
    record_b: {
      id: 202,
      source_system: 'INSURANCE',
      original_name: 'Rohit Raghavan',
      original_pan: 'ABCDE1234F',
      original_mobile: '9820011223',
      original_city: 'Bombay',
    },
    field_comparisons: [
      { field_name: 'PAN Number', value_a: 'ABCDE1234F', value_b: 'ABCDE1234F', status: 'MATCH', weight: 0.35, score: 1.0 },
      { field_name: 'Mobile Number', value_a: '9876543210', value_b: '9820011223', status: 'DIFFERENT', weight: 0.20, score: 0.0 },
      { field_name: 'Full Name', value_a: 'Rohit P. Raghavan', value_b: 'Rohit Raghavan', status: 'PARTIAL', weight: 0.12, score: 0.95 },
      { field_name: 'Semantic Match', value_a: 'PMS Account', value_b: 'Term Life', status: 'MATCH', weight: 0.08, score: 0.96 },
    ],
    final_score: 0.792,
  },
];

export const MOCK_OPPORTUNITIES = [
  {
    id: 1,
    golden_customer_id: 'GOLD-000101',
    customer_name: 'Rohit P. Raghavan',
    opportunity_type: 'CROSS_SELL',
    product_recommended: 'Wealth Management PMS (₹50L+)',
    score: 0.92,
    potential_value: 5000000,
    status: 'NEW',
    assigned_rm_id: 'RM-MUM-04',
    ai_reasoning: 'Customer holds ₹1.28 Cr across Equity & Mutual Funds with zero PMS mandate. High liquidity profile indicates prime cross-sell suitability.',
    eligibility_met: { min_aum_met: true, kyc_verified: true, risk_profile: 'AGGRESSIVE' },
    created_at: '2026-08-19T10:00:00Z',
  },
  {
    id: 2,
    golden_customer_id: 'GOLD-000102',
    customer_name: 'Sunita Mehra',
    opportunity_type: 'UPSELL',
    product_recommended: 'Structured Debt & Loan Against Securities (LAS)',
    score: 0.88,
    potential_value: 15000000,
    status: 'IN_PROGRESS',
    assigned_rm_id: 'RM-DEL-01',
    ai_reasoning: 'Customer has ₹4.5 Cr unencumbered Mutual Fund holdings and recently queried business expansion capital.',
    eligibility_met: { min_aum_met: true, pledgeable_assets: '₹3.2 Cr' },
    created_at: '2026-08-18T14:30:00Z',
  },
  {
    id: 3,
    golden_customer_id: 'GOLD-000103',
    customer_name: 'Vikram Aditya Singhania',
    opportunity_type: 'PROTECTION',
    product_recommended: 'Keyman Insurance & Corporate Trust',
    score: 0.85,
    potential_value: 20000000,
    status: 'ASSIGNED',
    assigned_rm_id: 'RM-BLR-02',
    ai_reasoning: 'High-value corporate demat holder (₹8.9 Cr AUM) with no business protection cover identified.',
    eligibility_met: { corporate_entity: true, gst_active: true },
    created_at: '2026-08-20T08:00:00Z',
  },
];

export const MOCK_CONFIG_RULES = [
  {
    id: 1,
    category: 'SOURCE_PRECEDENCE',
    rule_key: 'source_precedence_order',
    rule_value: { order: ['WEALTH', 'BANKING', 'EQUITY', 'MUTUAL_FUND', 'INSURANCE', 'LOAN'] },
    description: 'Hierarchical master source precedence for canonical customer field survivorship',
    version: 3,
    updated_by: 'admin',
    updated_at: '2026-08-18T10:00:00Z',
  },
  {
    id: 2,
    category: 'THRESHOLDS',
    rule_key: 'matching_thresholds',
    rule_value: { match_threshold: 0.85, review_threshold: 0.60 },
    description: 'Auto-match threshold (>=0.85) and human review trigger threshold (0.60 - 0.84)',
    version: 2,
    updated_by: 'admin',
    updated_at: '2026-08-15T12:00:00Z',
  },
  {
    id: 3,
    category: 'MATCHING_WEIGHTS',
    rule_key: 'feature_weights',
    rule_value: {
      pan_exact: 0.35,
      mobile_exact: 0.20,
      email_exact: 0.15,
      name_similarity: 0.12,
      name_semantic_similarity: 0.08,
      dob_exact: 0.05,
      city_similarity: 0.03,
      segment_exact: 0.02,
    },
    description: 'Normalized weights for 8-attribute identity resolution score calculation',
    version: 4,
    updated_by: 'admin',
    updated_at: '2026-08-19T16:30:00Z',
  },
];

export const MOCK_AUDIT_LOGS = [
  {
    id: 1042,
    timestamp: '2026-08-20T10:42:15Z',
    actor_username: 'reviewer_sarah',
    actor_role: 'REVIEWER',
    action: 'MERGE_APPROVE',
    entity_type: 'ReviewCase',
    entity_id: 'RV-1042',
    ip_address: '192.168.1.45',
    new_value: { decision: 'MATCH', golden_customer_id: 'GOLD-000101', notes: 'Approved after verifying physical KYC document' },
  },
  {
    id: 1041,
    timestamp: '2026-08-20T09:30:00Z',
    actor_username: 'admin',
    actor_role: 'ADMIN',
    action: 'MATCHING_RUN',
    entity_type: 'MatchingPipeline',
    entity_id: 'FULL_RUN',
    ip_address: '10.0.0.12',
    new_value: { pairs_evaluated: 18230, matches: 7560, reviews: 18, golden_created: 142 },
  },
  {
    id: 1040,
    timestamp: '2026-08-20T08:15:22Z',
    actor_username: 'admin',
    actor_role: 'ADMIN',
    action: 'DATA_INGEST',
    entity_type: 'SourceSystem',
    entity_id: 'EQUITY',
    ip_address: '10.0.0.12',
    new_value: { filename: 'equity_records.csv', records_ingested: 3120 },
  },
  {
    id: 1039,
    timestamp: '2026-08-19T17:20:00Z',
    actor_username: 'rm_rajesh',
    actor_role: 'RELATIONSHIP_MANAGER',
    action: 'OPPORTUNITY_UPDATE',
    entity_type: 'Opportunity',
    entity_id: 'OPP-102',
    ip_address: '192.168.1.88',
    new_value: { status: 'IN_PROGRESS', notes: 'Meeting scheduled with client on Friday' },
  },
  {
    id: 1038,
    timestamp: '2026-08-19T14:10:05Z',
    actor_username: 'admin',
    actor_role: 'ADMIN',
    action: 'CONFIG_CHANGE',
    entity_type: 'ConfigRule',
    entity_id: 'source_precedence_order',
    ip_address: '10.0.0.12',
    new_value: { order: ['WEALTH', 'BANKING', 'EQUITY', 'MUTUAL_FUND', 'INSURANCE', 'LOAN'] },
  },
];
